### ISSUE TITLE
nav part

### ISSUE THREAD

**Issue by Muhammed98Mustafa** [Recoded-Spark-Turkey-2022/movie-project-downtown-cinema#17]
- [x] HTML  and  CSS structure 
- functionally 
    - [x] movies
    - [x] Home
    - [x] Actor
    - [ ] about

**Comment by Muhammed98Mustafa** [comment]
![image](https://user-images.githubusercontent.com/106573190/201993091-db7ac2b4-c0e7-4cde-8f98-679df152654b.png)
when you hover over the movies part a movies list will drop

**Comment by Nadim-absi** [comment]
![image](https://user-images.githubusercontent.com/113457314/202122149-d18eb625-144d-4110-a4b4-15490d0d9693.png)
This part has been merged, now when clicking one the movies will change to that category
