### ISSUE TITLE
slides of  image 

### ISSUE THREAD

**Issue by Muhammed98Mustafa** [Recoded-Spark-Turkey-2022/movie-project-downtown-cinema#8]
- [x] header of the main page
- [x] slides of image

**Comment by Nadim-absi** [comment]
Great job, you got this.

Side note: are the buttons working or is this a bug on my side?

**Comment by Muhammed98Mustafa** [comment]
the buttons became bigger to make clicking easier, also the main header added

![image](https://user-images.githubusercontent.com/106573190/201824596-d5bce7d9-0aa7-4c28-8df6-b31d8e25485e.png)

**Comment by Nadim-absi** [comment]
Part Done
