### ISSUE TITLE
could not apply my code to all the scrollig section

### ISSUE THREAD

**Issue by trteel1** [Recoded-Spark-Turkey-2022/movie-project-downtown-cinema#9]
![image](https://user-images.githubusercontent.com/113727031/201544266-3af58a8e-e3a6-4fe0-bdce-583249062f40.png)
**in the img you can see that it is no applying**
![image](https://user-images.githubusercontent.com/113727031/201544358-82cfcffc-664e-45cb-bedb-8c77d39db41e.png)

**Comment by Muhammed98Mustafa** [comment]
I suggest showing the card without scroll, that will make your work easier
